### PR TITLE
support for multidate and multidateSeparator options

### PR DESCRIPTION
**Pull request by jelhan**
Adds support for `multidate` and `multidateSeparator` options of bootstrap-datepicker. If multidate is true, value is an array of ISO string.

### CODE REVIEW

**Comment by soulim** [comment]
Hey @jelhan! Thank you a lot for helping!

**Comment by soulim** [comment]
Seems like one piece is missing, but it should be easy to fix.

Look, `setupBootstrapDatepicker` [sets initial value of bootstrap-dateicker](https://github.com/jelhan/ember-cli-bootstrap-datepicker/blob/695d727878c41b89150a07a73a74dc7711e122f3/addon/components/datepicker-support.js#L38-L40), but it won't work correctly when `value` holds an array. Also [`setDates`](http://bootstrap-datepicker.readthedocs.org/en/release/methods.html#setdates) must be used to set multiple dates.

**Comment by soulim** [comment]
@jelhan thanks again for helping with the add-on! Sorry for delay with pull request review.

**Comment by jelhan** [comment]
Sorry, forgot that one. Fixed it and added tests.
Code would be much more clear and less complexive if we implement this one: #3

**Comment by jelhan** [comment]
Should the array of dates selected by bootstrap-datepicker be sorted before set to value? Currently first selected date is first one in array. Which order is prefered?

**Comment by soulim** [comment]
Would suggest not to sort an array of selected dates and be as close as possible to behaviour of the bootstrap-datepicker. It would help not to have compatibility problems with the datepicker, and also developers who use the add-on could except the same results as they would get from the original bootstrap-datepicker.

I would like to say huge "THANK YOU!" @jelhan for your help and nice ideas! Will merge this pull request tomorrow. 

Happy coding! :smile:

**Pull request merged**
