### PR TITLE
add changeMonth event

### PR DESCRIPTION
**Pull request by jelhan**
Also updates bootstrap-datepicker dependency to latest version.

### CODE REVIEW

**Comment by jelhan** [comment]
Includes #81.

Note that ''BootstrapDatepickerComponent: resets date when input is cleared'' is also failing on current master.

**Comment by soulim** [comment]
Thanks again @jelhan! 👍 

PR #81 is already merged into the master.

**Comment by soulim** [comment]
Great work @jelhan! 😃

**Comment by jelhan** [comment]
@soulim Thanks. And what a fast response! :-)

I just updated PR cause we now need to include `bootstrap` as dependency since it has been removed from `bootstrap-datepicker` dependencies: https://github.com/eternicode/bootstrap-datepicker/commit/a564ef669fd7c4a5f4abadf67c0ca78b7958bc46

**Comment by soulim** [comment]
This is great! Finally a build fails because of a failing test, not because of a missing file.

**Pull request merged**
