### PR TITLE
Fix for ember 1.13.x

### PR DESCRIPTION
**Pull request by jesenko**
Fixes issue #41

### CODE REVIEW

**Comment by soulim** [comment]
Thank you very much @jesenko! :+1:

**Comment by methanol** [comment]
Can you please release this? We are close to production and want to use this nicely created component! Thank you!

**Comment by soulim** [comment]
Thank you for kind words :smile: Will released a new version later today. Many people are already waiting for a new release.

**Comment by soulim** [comment]
@methanol you could install [v0.5.4][1] from the npm repository :wink:
It has been released a few minutes ago.

Thank you @jesenko and @methanol for being awesome and supporting this project :heart: 

[1]: https://github.com/soulim/ember-cli-bootstrap-datepicker/releases/tag/v0.5.4

**Comment by methanol** [comment]
@soulim "Remove style from attribute bindings" makes me also happy. Thanks a lot. I will try it out tomorrow. Keep up the good work!

**Pull request merged**
