### PR TITLE
Send action changeDate.

### PR DESCRIPTION
**Pull request by abuiles**
Currently if we want to do something every time the date changes we
need to use observers, with this approach we can avoid the use of
observers encouraging the use of Actions Up, Data Down.

### CODE REVIEW

**Comment by soulim** [comment]
Thank you for your contribution! At the moment the add-on follows the same strategy that all other Ember input fields use - you bind property to the input field and if you need to do something when the property changes its value, you use observers.

What's the main reason not to use observers?

**Comment by solsberg** [comment]
The input helper has an action that fires when the user makes an edit so you don't need to use observers 
http://guides.emberjs.com/v1.11.0/templates/input-helpers/

**Comment by abuiles** [comment]
@solsberg that does not work on this scenario, probably because the action is not really happening on the input.

**Comment by abuiles** [comment]
@soulim observers are expensive and lead to code which is hard to maintain and reason about  code, for example checking if  a value is null or not, with this pattern we avoid that. For upcoming versions of Ember this is the recommended pattern instead of observing

**Comment by solsberg** [comment]
@abuiles Exactly! My comment was intended to be in support of this PR as providing a similar pattern

**Comment by abuiles** [comment]
@solsberg :+1:

**Comment by soulim** [comment]
Okay, I've got your point. Thank you for the explanation. It will be awesome to add actions support to the add-on.

@abuiles can you also update README? I think this feature needs a short explanation and a code example. You could make a separate section and use "Available options" section as example.

Please squash all commits, when you are satisfied with results.

**Comment by soulim** [comment]
Thank you @abuiles! :+1:

**Comment by westlywright** [comment]
I would be super grateful if either @soulim or @abuiles could explain how this works in practice!

**Comment by soulim** [comment]
@westlywright this's an example for you.

Just imagine you a template that uses the component and a controller where you would like to do something with a selected date.

```hbs
{{!-- app/templates/foo.hbs  --}}

{{bootstrap-datepicker value=model.expiresAt}}
```

```js
// app/controllers/foo.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    changeDate: function (value) {
      // ...
    }
  }
});
```

Every time you select a new date using the component it will send `changeDate` action and the controller will handle this action. So you don't need to use an observer to monitor changes of `expiresAt` value.

**Comment by solsberg** [comment]
@soulim any plans for a new release which will incorporate this functionality?

**Comment by soulim** [comment]
@solsberg just released `0.5.2` that includes this feature and a couple more interesting things.

**Pull request merged**
